SUBDIRS = Lesson1 Lesson2 Lesson3 Lesson4 Lesson5 Lesson6

all:
	for i in $(SUBDIRS); do cd $$i && $(MAKE) all; cd ..; done

lesson1 :
	cd Lesson1; make


#empty dist and distdir to let top-level 'make' do its job
dist :

distdir :

check :

clean:
	for i in $(SUBDIRS); do cd $$i && $(MAKE) clean; cd ..; done
